### ISSUE TITLE
Scholarship list: pagination

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#190]
**User Story**
_As a user, I can browse through the scholarship list **one page at a time**._

Why one page? To save data for both the users and us :)

- [ ] [Pagination](https://material-ui.com/components/pagination/) component at the bottom of the page
- [ ] Pagination functionality
  - [ ] URL parameter determines which page it's on.
  - [ ] URL updated on next/previous page.

**Comment by josueetcom** [comment]
Closing this. I'll instead keep the URL parameter support as its own issue for the official launch date.

**Comment by josueetcom** [comment]
Actually, I'll reopen this. Helps to see what pieces are still incomplete.
